//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Health.Fhir.SqlServer.Features.Schema.Model
{
    using Microsoft.Health.SqlServer.Features.Client;
    using Microsoft.Health.SqlServer.Features.Schema.Model;

    internal class BigintListTableValuedParameterDefinition : TableValuedParameterDefinition<BigintListRow>
    {
        internal BigintListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.BigintList")
        {
        }

        internal readonly BigIntColumn Id = new BigIntColumn("Id");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { Id };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, BigintListRow rowData)
        {
            Id.Set(record, 0, rowData.Id);
        }
    }

    internal struct BigintListRow
    {
        internal BigintListRow(System.Int64 Id)
        {
            this.Id = Id;
        }

        internal System.Int64 Id { get; }
    }

    internal class BulkReindexResourceTableTypeV1TableValuedParameterDefinition : TableValuedParameterDefinition<BulkReindexResourceTableTypeV1Row>
    {
        internal BulkReindexResourceTableTypeV1TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.BulkReindexResourceTableType_1")
        {
        }

        internal readonly IntColumn Offset = new IntColumn("Offset");
        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly VarCharColumn ResourceId = new VarCharColumn("ResourceId", 64, "Latin1_General_100_CS_AS");
        internal readonly NullableIntColumn ETag = new NullableIntColumn("ETag");
        internal readonly VarCharColumn SearchParamHash = new VarCharColumn("SearchParamHash", 64);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { Offset, ResourceTypeId, ResourceId, ETag, SearchParamHash };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, BulkReindexResourceTableTypeV1Row rowData)
        {
            Offset.Set(record, 0, rowData.Offset);
            ResourceTypeId.Set(record, 1, rowData.ResourceTypeId);
            ResourceId.Set(record, 2, rowData.ResourceId);
            ETag.Set(record, 3, rowData.ETag);
            SearchParamHash.Set(record, 4, rowData.SearchParamHash);
        }
    }

    internal struct BulkReindexResourceTableTypeV1Row
    {
        internal BulkReindexResourceTableTypeV1Row(System.Int32 Offset, System.Int16 ResourceTypeId, System.String ResourceId, System.Nullable<System.Int32> ETag, System.String SearchParamHash)
        {
            this.Offset = Offset;
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceId = ResourceId;
            this.ETag = ETag;
            this.SearchParamHash = SearchParamHash;
        }

        internal System.Int32 Offset { get; }
        internal System.Int16 ResourceTypeId { get; }
        internal System.String ResourceId { get; }
        internal System.Nullable<System.Int32> ETag { get; }
        internal System.String SearchParamHash { get; }
    }

    internal class DateTimeSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<DateTimeSearchParamListRow>
    {
        internal DateTimeSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.DateTimeSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly DateTimeOffsetColumn StartDateTime = new DateTimeOffsetColumn("StartDateTime", 7);
        internal readonly DateTimeOffsetColumn EndDateTime = new DateTimeOffsetColumn("EndDateTime", 7);
        internal readonly BitColumn IsLongerThanADay = new BitColumn("IsLongerThanADay");
        internal readonly BitColumn IsMin = new BitColumn("IsMin");
        internal readonly BitColumn IsMax = new BitColumn("IsMax");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, StartDateTime, EndDateTime, IsLongerThanADay, IsMin, IsMax };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, DateTimeSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            StartDateTime.Set(record, 3, rowData.StartDateTime);
            EndDateTime.Set(record, 4, rowData.EndDateTime);
            IsLongerThanADay.Set(record, 5, rowData.IsLongerThanADay);
            IsMin.Set(record, 6, rowData.IsMin);
            IsMax.Set(record, 7, rowData.IsMax);
        }
    }

    internal struct DateTimeSearchParamListRow
    {
        internal DateTimeSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.DateTimeOffset StartDateTime, System.DateTimeOffset EndDateTime, System.Boolean IsLongerThanADay, System.Boolean IsMin, System.Boolean IsMax)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.StartDateTime = StartDateTime;
            this.EndDateTime = EndDateTime;
            this.IsLongerThanADay = IsLongerThanADay;
            this.IsMin = IsMin;
            this.IsMax = IsMax;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.DateTimeOffset StartDateTime { get; }
        internal System.DateTimeOffset EndDateTime { get; }
        internal System.Boolean IsLongerThanADay { get; }
        internal System.Boolean IsMin { get; }
        internal System.Boolean IsMax { get; }
    }

    internal class NumberSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<NumberSearchParamListRow>
    {
        internal NumberSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.NumberSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableDecimalColumn SingleValue = new NullableDecimalColumn("SingleValue", 36, 18);
        internal readonly NullableDecimalColumn LowValue = new NullableDecimalColumn("LowValue", 36, 18);
        internal readonly NullableDecimalColumn HighValue = new NullableDecimalColumn("HighValue", 36, 18);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SingleValue, LowValue, HighValue };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, NumberSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SingleValue.Set(record, 3, rowData.SingleValue);
            LowValue.Set(record, 4, rowData.LowValue);
            HighValue.Set(record, 5, rowData.HighValue);
        }
    }

    internal struct NumberSearchParamListRow
    {
        internal NumberSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Decimal> SingleValue, System.Nullable<System.Decimal> LowValue, System.Nullable<System.Decimal> HighValue)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SingleValue = SingleValue;
            this.LowValue = LowValue;
            this.HighValue = HighValue;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Decimal> SingleValue { get; }
        internal System.Nullable<System.Decimal> LowValue { get; }
        internal System.Nullable<System.Decimal> HighValue { get; }
    }

    internal class QuantitySearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<QuantitySearchParamListRow>
    {
        internal QuantitySearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.QuantitySearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableIntColumn SystemId = new NullableIntColumn("SystemId");
        internal readonly NullableIntColumn QuantityCodeId = new NullableIntColumn("QuantityCodeId");
        internal readonly NullableDecimalColumn SingleValue = new NullableDecimalColumn("SingleValue", 36, 18);
        internal readonly NullableDecimalColumn LowValue = new NullableDecimalColumn("LowValue", 36, 18);
        internal readonly NullableDecimalColumn HighValue = new NullableDecimalColumn("HighValue", 36, 18);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SystemId, QuantityCodeId, SingleValue, LowValue, HighValue };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, QuantitySearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SystemId.Set(record, 3, rowData.SystemId);
            QuantityCodeId.Set(record, 4, rowData.QuantityCodeId);
            SingleValue.Set(record, 5, rowData.SingleValue);
            LowValue.Set(record, 6, rowData.LowValue);
            HighValue.Set(record, 7, rowData.HighValue);
        }
    }

    internal struct QuantitySearchParamListRow
    {
        internal QuantitySearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Int32> SystemId, System.Nullable<System.Int32> QuantityCodeId, System.Nullable<System.Decimal> SingleValue, System.Nullable<System.Decimal> LowValue, System.Nullable<System.Decimal> HighValue)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SystemId = SystemId;
            this.QuantityCodeId = QuantityCodeId;
            this.SingleValue = SingleValue;
            this.LowValue = LowValue;
            this.HighValue = HighValue;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Int32> SystemId { get; }
        internal System.Nullable<System.Int32> QuantityCodeId { get; }
        internal System.Nullable<System.Decimal> SingleValue { get; }
        internal System.Nullable<System.Decimal> LowValue { get; }
        internal System.Nullable<System.Decimal> HighValue { get; }
    }

    internal class ReferenceSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<ReferenceSearchParamListRow>
    {
        internal ReferenceSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.ReferenceSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableVarCharColumn BaseUri = new NullableVarCharColumn("BaseUri", 128, "Latin1_General_100_CS_AS");
        internal readonly NullableSmallIntColumn ReferenceResourceTypeId = new NullableSmallIntColumn("ReferenceResourceTypeId");
        internal readonly VarCharColumn ReferenceResourceId = new VarCharColumn("ReferenceResourceId", 64, "Latin1_General_100_CS_AS");
        internal readonly NullableIntColumn ReferenceResourceVersion = new NullableIntColumn("ReferenceResourceVersion");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, BaseUri, ReferenceResourceTypeId, ReferenceResourceId, ReferenceResourceVersion };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, ReferenceSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            BaseUri.Set(record, 3, rowData.BaseUri);
            ReferenceResourceTypeId.Set(record, 4, rowData.ReferenceResourceTypeId);
            ReferenceResourceId.Set(record, 5, rowData.ReferenceResourceId);
            ReferenceResourceVersion.Set(record, 6, rowData.ReferenceResourceVersion);
        }
    }

    internal struct ReferenceSearchParamListRow
    {
        internal ReferenceSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.String BaseUri, System.Nullable<System.Int16> ReferenceResourceTypeId, System.String ReferenceResourceId, System.Nullable<System.Int32> ReferenceResourceVersion)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.BaseUri = BaseUri;
            this.ReferenceResourceTypeId = ReferenceResourceTypeId;
            this.ReferenceResourceId = ReferenceResourceId;
            this.ReferenceResourceVersion = ReferenceResourceVersion;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.String BaseUri { get; }
        internal System.Nullable<System.Int16> ReferenceResourceTypeId { get; }
        internal System.String ReferenceResourceId { get; }
        internal System.Nullable<System.Int32> ReferenceResourceVersion { get; }
    }

    internal class ReferenceTokenCompositeSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<ReferenceTokenCompositeSearchParamListRow>
    {
        internal ReferenceTokenCompositeSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.ReferenceTokenCompositeSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableVarCharColumn BaseUri1 = new NullableVarCharColumn("BaseUri1", 128, "Latin1_General_100_CS_AS");
        internal readonly NullableSmallIntColumn ReferenceResourceTypeId1 = new NullableSmallIntColumn("ReferenceResourceTypeId1");
        internal readonly VarCharColumn ReferenceResourceId1 = new VarCharColumn("ReferenceResourceId1", 64, "Latin1_General_100_CS_AS");
        internal readonly NullableIntColumn ReferenceResourceVersion1 = new NullableIntColumn("ReferenceResourceVersion1");
        internal readonly NullableIntColumn SystemId2 = new NullableIntColumn("SystemId2");
        internal readonly VarCharColumn Code2 = new VarCharColumn("Code2", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow2 = new NullableVarCharColumn("CodeOverflow2", -1, "Latin1_General_100_CS_AS");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, BaseUri1, ReferenceResourceTypeId1, ReferenceResourceId1, ReferenceResourceVersion1, SystemId2, Code2, CodeOverflow2 };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, ReferenceTokenCompositeSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            BaseUri1.Set(record, 3, rowData.BaseUri1);
            ReferenceResourceTypeId1.Set(record, 4, rowData.ReferenceResourceTypeId1);
            ReferenceResourceId1.Set(record, 5, rowData.ReferenceResourceId1);
            ReferenceResourceVersion1.Set(record, 6, rowData.ReferenceResourceVersion1);
            SystemId2.Set(record, 7, rowData.SystemId2);
            Code2.Set(record, 8, rowData.Code2);
            CodeOverflow2.Set(record, 9, rowData.CodeOverflow2);
        }
    }

    internal struct ReferenceTokenCompositeSearchParamListRow
    {
        internal ReferenceTokenCompositeSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.String BaseUri1, System.Nullable<System.Int16> ReferenceResourceTypeId1, System.String ReferenceResourceId1, System.Nullable<System.Int32> ReferenceResourceVersion1, System.Nullable<System.Int32> SystemId2, System.String Code2, System.String CodeOverflow2)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.BaseUri1 = BaseUri1;
            this.ReferenceResourceTypeId1 = ReferenceResourceTypeId1;
            this.ReferenceResourceId1 = ReferenceResourceId1;
            this.ReferenceResourceVersion1 = ReferenceResourceVersion1;
            this.SystemId2 = SystemId2;
            this.Code2 = Code2;
            this.CodeOverflow2 = CodeOverflow2;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.String BaseUri1 { get; }
        internal System.Nullable<System.Int16> ReferenceResourceTypeId1 { get; }
        internal System.String ReferenceResourceId1 { get; }
        internal System.Nullable<System.Int32> ReferenceResourceVersion1 { get; }
        internal System.Nullable<System.Int32> SystemId2 { get; }
        internal System.String Code2 { get; }
        internal System.String CodeOverflow2 { get; }
    }

    internal class ResourceDateKeyListTableValuedParameterDefinition : TableValuedParameterDefinition<ResourceDateKeyListRow>
    {
        internal ResourceDateKeyListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.ResourceDateKeyList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly VarCharColumn ResourceId = new VarCharColumn("ResourceId", 64, "Latin1_General_100_CS_AS");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceId, ResourceSurrogateId };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, ResourceDateKeyListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceId.Set(record, 1, rowData.ResourceId);
            ResourceSurrogateId.Set(record, 2, rowData.ResourceSurrogateId);
        }
    }

    internal struct ResourceDateKeyListRow
    {
        internal ResourceDateKeyListRow(System.Int16 ResourceTypeId, System.String ResourceId, System.Int64 ResourceSurrogateId)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceId = ResourceId;
            this.ResourceSurrogateId = ResourceSurrogateId;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.String ResourceId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
    }

    internal class ResourceKeyListTableValuedParameterDefinition : TableValuedParameterDefinition<ResourceKeyListRow>
    {
        internal ResourceKeyListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.ResourceKeyList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly VarCharColumn ResourceId = new VarCharColumn("ResourceId", 64, "Latin1_General_100_CS_AS");
        internal readonly NullableIntColumn Version = new NullableIntColumn("Version");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceId, Version };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, ResourceKeyListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceId.Set(record, 1, rowData.ResourceId);
            Version.Set(record, 2, rowData.Version);
        }
    }

    internal struct ResourceKeyListRow
    {
        internal ResourceKeyListRow(System.Int16 ResourceTypeId, System.String ResourceId, System.Nullable<System.Int32> Version)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceId = ResourceId;
            this.Version = Version;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.String ResourceId { get; }
        internal System.Nullable<System.Int32> Version { get; }
    }

    internal class ResourceListTableValuedParameterDefinition : TableValuedParameterDefinition<ResourceListRow>
    {
        internal ResourceListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.ResourceList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly VarCharColumn ResourceId = new VarCharColumn("ResourceId", 64, "Latin1_General_100_CS_AS");
        internal readonly IntColumn Version = new IntColumn("Version");
        internal readonly BitColumn HasVersionToCompare = new BitColumn("HasVersionToCompare");
        internal readonly BitColumn IsDeleted = new BitColumn("IsDeleted");
        internal readonly BitColumn IsHistory = new BitColumn("IsHistory");
        internal readonly BitColumn KeepHistory = new BitColumn("KeepHistory");
        internal readonly VarBinaryColumn RawResource = new VarBinaryColumn("RawResource", -1);
        internal readonly BitColumn IsRawResourceMetaSet = new BitColumn("IsRawResourceMetaSet");
        internal readonly NullableVarCharColumn RequestMethod = new NullableVarCharColumn("RequestMethod", 10);
        internal readonly NullableVarCharColumn SearchParamHash = new NullableVarCharColumn("SearchParamHash", 64);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, ResourceId, Version, HasVersionToCompare, IsDeleted, IsHistory, KeepHistory, RawResource, IsRawResourceMetaSet, RequestMethod, SearchParamHash };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, ResourceListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            ResourceId.Set(record, 2, rowData.ResourceId);
            Version.Set(record, 3, rowData.Version);
            HasVersionToCompare.Set(record, 4, rowData.HasVersionToCompare);
            IsDeleted.Set(record, 5, rowData.IsDeleted);
            IsHistory.Set(record, 6, rowData.IsHistory);
            KeepHistory.Set(record, 7, rowData.KeepHistory);
            RawResource.Set(record, 8, rowData.RawResource);
            IsRawResourceMetaSet.Set(record, 9, rowData.IsRawResourceMetaSet);
            RequestMethod.Set(record, 10, rowData.RequestMethod);
            SearchParamHash.Set(record, 11, rowData.SearchParamHash);
        }
    }

    internal struct ResourceListRow
    {
        internal ResourceListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.String ResourceId, System.Int32 Version, System.Boolean HasVersionToCompare, System.Boolean IsDeleted, System.Boolean IsHistory, System.Boolean KeepHistory, global::System.IO.Stream RawResource, System.Boolean IsRawResourceMetaSet, System.String RequestMethod, System.String SearchParamHash)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.ResourceId = ResourceId;
            this.Version = Version;
            this.HasVersionToCompare = HasVersionToCompare;
            this.IsDeleted = IsDeleted;
            this.IsHistory = IsHistory;
            this.KeepHistory = KeepHistory;
            this.RawResource = RawResource;
            this.IsRawResourceMetaSet = IsRawResourceMetaSet;
            this.RequestMethod = RequestMethod;
            this.SearchParamHash = SearchParamHash;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.String ResourceId { get; }
        internal System.Int32 Version { get; }
        internal System.Boolean HasVersionToCompare { get; }
        internal System.Boolean IsDeleted { get; }
        internal System.Boolean IsHistory { get; }
        internal System.Boolean KeepHistory { get; }
        internal global::System.IO.Stream RawResource { get; }
        internal System.Boolean IsRawResourceMetaSet { get; }
        internal System.String RequestMethod { get; }
        internal System.String SearchParamHash { get; }
    }

    internal class ResourceWriteClaimListTableValuedParameterDefinition : TableValuedParameterDefinition<ResourceWriteClaimListRow>
    {
        internal ResourceWriteClaimListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.ResourceWriteClaimList")
        {
        }

        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly TinyIntColumn ClaimTypeId = new TinyIntColumn("ClaimTypeId");
        internal readonly NVarCharColumn ClaimValue = new NVarCharColumn("ClaimValue", 128);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceSurrogateId, ClaimTypeId, ClaimValue };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, ResourceWriteClaimListRow rowData)
        {
            ResourceSurrogateId.Set(record, 0, rowData.ResourceSurrogateId);
            ClaimTypeId.Set(record, 1, rowData.ClaimTypeId);
            ClaimValue.Set(record, 2, rowData.ClaimValue);
        }
    }

    internal struct ResourceWriteClaimListRow
    {
        internal ResourceWriteClaimListRow(System.Int64 ResourceSurrogateId, System.Byte ClaimTypeId, System.String ClaimValue)
        {
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.ClaimTypeId = ClaimTypeId;
            this.ClaimValue = ClaimValue;
        }

        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Byte ClaimTypeId { get; }
        internal System.String ClaimValue { get; }
    }

    internal class SearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<SearchParamListRow>
    {
        internal SearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.SearchParamList")
        {
        }

        internal readonly VarCharColumn Uri = new VarCharColumn("Uri", 128, "Latin1_General_100_CS_AS");
        internal readonly VarCharColumn Status = new VarCharColumn("Status", 20);
        internal readonly BitColumn IsPartiallySupported = new BitColumn("IsPartiallySupported");
        internal readonly DateTimeOffsetColumn LastUpdated = new DateTimeOffsetColumn("LastUpdated", 7);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { Uri, Status, IsPartiallySupported, LastUpdated };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, SearchParamListRow rowData)
        {
            Uri.Set(record, 0, rowData.Uri);
            Status.Set(record, 1, rowData.Status);
            IsPartiallySupported.Set(record, 2, rowData.IsPartiallySupported);
            LastUpdated.Set(record, 3, rowData.LastUpdated);
        }
    }

    internal struct SearchParamListRow
    {
        internal SearchParamListRow(System.String Uri, System.String Status, System.Boolean IsPartiallySupported, System.DateTimeOffset LastUpdated)
        {
            this.Uri = Uri;
            this.Status = Status;
            this.IsPartiallySupported = IsPartiallySupported;
            this.LastUpdated = LastUpdated;
        }

        internal System.String Uri { get; }
        internal System.String Status { get; }
        internal System.Boolean IsPartiallySupported { get; }
        internal System.DateTimeOffset LastUpdated { get; }
    }

    internal class SearchParamTableTypeV2TableValuedParameterDefinition : TableValuedParameterDefinition<SearchParamTableTypeV2Row>
    {
        internal SearchParamTableTypeV2TableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.SearchParamTableType_2")
        {
        }

        internal readonly VarCharColumn Uri = new VarCharColumn("Uri", 128, "Latin1_General_100_CS_AS");
        internal readonly VarCharColumn Status = new VarCharColumn("Status", 20);
        internal readonly BitColumn IsPartiallySupported = new BitColumn("IsPartiallySupported");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { Uri, Status, IsPartiallySupported };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, SearchParamTableTypeV2Row rowData)
        {
            Uri.Set(record, 0, rowData.Uri);
            Status.Set(record, 1, rowData.Status);
            IsPartiallySupported.Set(record, 2, rowData.IsPartiallySupported);
        }
    }

    internal struct SearchParamTableTypeV2Row
    {
        internal SearchParamTableTypeV2Row(System.String Uri, System.String Status, System.Boolean IsPartiallySupported)
        {
            this.Uri = Uri;
            this.Status = Status;
            this.IsPartiallySupported = IsPartiallySupported;
        }

        internal System.String Uri { get; }
        internal System.String Status { get; }
        internal System.Boolean IsPartiallySupported { get; }
    }

    internal class StringListTableValuedParameterDefinition : TableValuedParameterDefinition<StringListRow>
    {
        internal StringListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.StringList")
        {
        }

        internal readonly VarCharColumn String = new VarCharColumn("String", -1);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { String };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, StringListRow rowData)
        {
            String.Set(record, 0, rowData.String);
        }
    }

    internal struct StringListRow
    {
        internal StringListRow(System.String String)
        {
            this.String = String;
        }

        internal System.String String { get; }
    }

    internal class StringSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<StringSearchParamListRow>
    {
        internal StringSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.StringSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NVarCharColumn Text = new NVarCharColumn("Text", 256, "Latin1_General_100_CI_AI_SC");
        internal readonly NullableNVarCharColumn TextOverflow = new NullableNVarCharColumn("TextOverflow", -1, "Latin1_General_100_CI_AI_SC");
        internal readonly BitColumn IsMin = new BitColumn("IsMin");
        internal readonly BitColumn IsMax = new BitColumn("IsMax");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, Text, TextOverflow, IsMin, IsMax };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, StringSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            Text.Set(record, 3, rowData.Text);
            TextOverflow.Set(record, 4, rowData.TextOverflow);
            IsMin.Set(record, 5, rowData.IsMin);
            IsMax.Set(record, 6, rowData.IsMax);
        }
    }

    internal struct StringSearchParamListRow
    {
        internal StringSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.String Text, System.String TextOverflow, System.Boolean IsMin, System.Boolean IsMax)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.Text = Text;
            this.TextOverflow = TextOverflow;
            this.IsMin = IsMin;
            this.IsMax = IsMax;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.String Text { get; }
        internal System.String TextOverflow { get; }
        internal System.Boolean IsMin { get; }
        internal System.Boolean IsMax { get; }
    }

    internal class TokenDateTimeCompositeSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<TokenDateTimeCompositeSearchParamListRow>
    {
        internal TokenDateTimeCompositeSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.TokenDateTimeCompositeSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableIntColumn SystemId1 = new NullableIntColumn("SystemId1");
        internal readonly VarCharColumn Code1 = new VarCharColumn("Code1", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow1 = new NullableVarCharColumn("CodeOverflow1", -1, "Latin1_General_100_CS_AS");
        internal readonly DateTimeOffsetColumn StartDateTime2 = new DateTimeOffsetColumn("StartDateTime2", 7);
        internal readonly DateTimeOffsetColumn EndDateTime2 = new DateTimeOffsetColumn("EndDateTime2", 7);
        internal readonly BitColumn IsLongerThanADay2 = new BitColumn("IsLongerThanADay2");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SystemId1, Code1, CodeOverflow1, StartDateTime2, EndDateTime2, IsLongerThanADay2 };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, TokenDateTimeCompositeSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SystemId1.Set(record, 3, rowData.SystemId1);
            Code1.Set(record, 4, rowData.Code1);
            CodeOverflow1.Set(record, 5, rowData.CodeOverflow1);
            StartDateTime2.Set(record, 6, rowData.StartDateTime2);
            EndDateTime2.Set(record, 7, rowData.EndDateTime2);
            IsLongerThanADay2.Set(record, 8, rowData.IsLongerThanADay2);
        }
    }

    internal struct TokenDateTimeCompositeSearchParamListRow
    {
        internal TokenDateTimeCompositeSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Int32> SystemId1, System.String Code1, System.String CodeOverflow1, System.DateTimeOffset StartDateTime2, System.DateTimeOffset EndDateTime2, System.Boolean IsLongerThanADay2)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SystemId1 = SystemId1;
            this.Code1 = Code1;
            this.CodeOverflow1 = CodeOverflow1;
            this.StartDateTime2 = StartDateTime2;
            this.EndDateTime2 = EndDateTime2;
            this.IsLongerThanADay2 = IsLongerThanADay2;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Int32> SystemId1 { get; }
        internal System.String Code1 { get; }
        internal System.String CodeOverflow1 { get; }
        internal System.DateTimeOffset StartDateTime2 { get; }
        internal System.DateTimeOffset EndDateTime2 { get; }
        internal System.Boolean IsLongerThanADay2 { get; }
    }

    internal class TokenNumberNumberCompositeSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<TokenNumberNumberCompositeSearchParamListRow>
    {
        internal TokenNumberNumberCompositeSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.TokenNumberNumberCompositeSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableIntColumn SystemId1 = new NullableIntColumn("SystemId1");
        internal readonly VarCharColumn Code1 = new VarCharColumn("Code1", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow1 = new NullableVarCharColumn("CodeOverflow1", -1, "Latin1_General_100_CS_AS");
        internal readonly NullableDecimalColumn SingleValue2 = new NullableDecimalColumn("SingleValue2", 36, 18);
        internal readonly NullableDecimalColumn LowValue2 = new NullableDecimalColumn("LowValue2", 36, 18);
        internal readonly NullableDecimalColumn HighValue2 = new NullableDecimalColumn("HighValue2", 36, 18);
        internal readonly NullableDecimalColumn SingleValue3 = new NullableDecimalColumn("SingleValue3", 36, 18);
        internal readonly NullableDecimalColumn LowValue3 = new NullableDecimalColumn("LowValue3", 36, 18);
        internal readonly NullableDecimalColumn HighValue3 = new NullableDecimalColumn("HighValue3", 36, 18);
        internal readonly BitColumn HasRange = new BitColumn("HasRange");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SystemId1, Code1, CodeOverflow1, SingleValue2, LowValue2, HighValue2, SingleValue3, LowValue3, HighValue3, HasRange };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, TokenNumberNumberCompositeSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SystemId1.Set(record, 3, rowData.SystemId1);
            Code1.Set(record, 4, rowData.Code1);
            CodeOverflow1.Set(record, 5, rowData.CodeOverflow1);
            SingleValue2.Set(record, 6, rowData.SingleValue2);
            LowValue2.Set(record, 7, rowData.LowValue2);
            HighValue2.Set(record, 8, rowData.HighValue2);
            SingleValue3.Set(record, 9, rowData.SingleValue3);
            LowValue3.Set(record, 10, rowData.LowValue3);
            HighValue3.Set(record, 11, rowData.HighValue3);
            HasRange.Set(record, 12, rowData.HasRange);
        }
    }

    internal struct TokenNumberNumberCompositeSearchParamListRow
    {
        internal TokenNumberNumberCompositeSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Int32> SystemId1, System.String Code1, System.String CodeOverflow1, System.Nullable<System.Decimal> SingleValue2, System.Nullable<System.Decimal> LowValue2, System.Nullable<System.Decimal> HighValue2, System.Nullable<System.Decimal> SingleValue3, System.Nullable<System.Decimal> LowValue3, System.Nullable<System.Decimal> HighValue3, System.Boolean HasRange)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SystemId1 = SystemId1;
            this.Code1 = Code1;
            this.CodeOverflow1 = CodeOverflow1;
            this.SingleValue2 = SingleValue2;
            this.LowValue2 = LowValue2;
            this.HighValue2 = HighValue2;
            this.SingleValue3 = SingleValue3;
            this.LowValue3 = LowValue3;
            this.HighValue3 = HighValue3;
            this.HasRange = HasRange;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Int32> SystemId1 { get; }
        internal System.String Code1 { get; }
        internal System.String CodeOverflow1 { get; }
        internal System.Nullable<System.Decimal> SingleValue2 { get; }
        internal System.Nullable<System.Decimal> LowValue2 { get; }
        internal System.Nullable<System.Decimal> HighValue2 { get; }
        internal System.Nullable<System.Decimal> SingleValue3 { get; }
        internal System.Nullable<System.Decimal> LowValue3 { get; }
        internal System.Nullable<System.Decimal> HighValue3 { get; }
        internal System.Boolean HasRange { get; }
    }

    internal class TokenQuantityCompositeSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<TokenQuantityCompositeSearchParamListRow>
    {
        internal TokenQuantityCompositeSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.TokenQuantityCompositeSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableIntColumn SystemId1 = new NullableIntColumn("SystemId1");
        internal readonly VarCharColumn Code1 = new VarCharColumn("Code1", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow1 = new NullableVarCharColumn("CodeOverflow1", -1, "Latin1_General_100_CS_AS");
        internal readonly NullableIntColumn SystemId2 = new NullableIntColumn("SystemId2");
        internal readonly NullableIntColumn QuantityCodeId2 = new NullableIntColumn("QuantityCodeId2");
        internal readonly NullableDecimalColumn SingleValue2 = new NullableDecimalColumn("SingleValue2", 36, 18);
        internal readonly NullableDecimalColumn LowValue2 = new NullableDecimalColumn("LowValue2", 36, 18);
        internal readonly NullableDecimalColumn HighValue2 = new NullableDecimalColumn("HighValue2", 36, 18);

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SystemId1, Code1, CodeOverflow1, SystemId2, QuantityCodeId2, SingleValue2, LowValue2, HighValue2 };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, TokenQuantityCompositeSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SystemId1.Set(record, 3, rowData.SystemId1);
            Code1.Set(record, 4, rowData.Code1);
            CodeOverflow1.Set(record, 5, rowData.CodeOverflow1);
            SystemId2.Set(record, 6, rowData.SystemId2);
            QuantityCodeId2.Set(record, 7, rowData.QuantityCodeId2);
            SingleValue2.Set(record, 8, rowData.SingleValue2);
            LowValue2.Set(record, 9, rowData.LowValue2);
            HighValue2.Set(record, 10, rowData.HighValue2);
        }
    }

    internal struct TokenQuantityCompositeSearchParamListRow
    {
        internal TokenQuantityCompositeSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Int32> SystemId1, System.String Code1, System.String CodeOverflow1, System.Nullable<System.Int32> SystemId2, System.Nullable<System.Int32> QuantityCodeId2, System.Nullable<System.Decimal> SingleValue2, System.Nullable<System.Decimal> LowValue2, System.Nullable<System.Decimal> HighValue2)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SystemId1 = SystemId1;
            this.Code1 = Code1;
            this.CodeOverflow1 = CodeOverflow1;
            this.SystemId2 = SystemId2;
            this.QuantityCodeId2 = QuantityCodeId2;
            this.SingleValue2 = SingleValue2;
            this.LowValue2 = LowValue2;
            this.HighValue2 = HighValue2;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Int32> SystemId1 { get; }
        internal System.String Code1 { get; }
        internal System.String CodeOverflow1 { get; }
        internal System.Nullable<System.Int32> SystemId2 { get; }
        internal System.Nullable<System.Int32> QuantityCodeId2 { get; }
        internal System.Nullable<System.Decimal> SingleValue2 { get; }
        internal System.Nullable<System.Decimal> LowValue2 { get; }
        internal System.Nullable<System.Decimal> HighValue2 { get; }
    }

    internal class TokenSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<TokenSearchParamListRow>
    {
        internal TokenSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.TokenSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableIntColumn SystemId = new NullableIntColumn("SystemId");
        internal readonly VarCharColumn Code = new VarCharColumn("Code", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow = new NullableVarCharColumn("CodeOverflow", -1, "Latin1_General_100_CS_AS");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SystemId, Code, CodeOverflow };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, TokenSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SystemId.Set(record, 3, rowData.SystemId);
            Code.Set(record, 4, rowData.Code);
            CodeOverflow.Set(record, 5, rowData.CodeOverflow);
        }
    }

    internal struct TokenSearchParamListRow
    {
        internal TokenSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Int32> SystemId, System.String Code, System.String CodeOverflow)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SystemId = SystemId;
            this.Code = Code;
            this.CodeOverflow = CodeOverflow;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Int32> SystemId { get; }
        internal System.String Code { get; }
        internal System.String CodeOverflow { get; }
    }

    internal class TokenStringCompositeSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<TokenStringCompositeSearchParamListRow>
    {
        internal TokenStringCompositeSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.TokenStringCompositeSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableIntColumn SystemId1 = new NullableIntColumn("SystemId1");
        internal readonly VarCharColumn Code1 = new VarCharColumn("Code1", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow1 = new NullableVarCharColumn("CodeOverflow1", -1, "Latin1_General_100_CS_AS");
        internal readonly NVarCharColumn Text2 = new NVarCharColumn("Text2", 256, "Latin1_General_100_CI_AI_SC");
        internal readonly NullableNVarCharColumn TextOverflow2 = new NullableNVarCharColumn("TextOverflow2", -1, "Latin1_General_100_CI_AI_SC");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SystemId1, Code1, CodeOverflow1, Text2, TextOverflow2 };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, TokenStringCompositeSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SystemId1.Set(record, 3, rowData.SystemId1);
            Code1.Set(record, 4, rowData.Code1);
            CodeOverflow1.Set(record, 5, rowData.CodeOverflow1);
            Text2.Set(record, 6, rowData.Text2);
            TextOverflow2.Set(record, 7, rowData.TextOverflow2);
        }
    }

    internal struct TokenStringCompositeSearchParamListRow
    {
        internal TokenStringCompositeSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Int32> SystemId1, System.String Code1, System.String CodeOverflow1, System.String Text2, System.String TextOverflow2)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SystemId1 = SystemId1;
            this.Code1 = Code1;
            this.CodeOverflow1 = CodeOverflow1;
            this.Text2 = Text2;
            this.TextOverflow2 = TextOverflow2;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Int32> SystemId1 { get; }
        internal System.String Code1 { get; }
        internal System.String CodeOverflow1 { get; }
        internal System.String Text2 { get; }
        internal System.String TextOverflow2 { get; }
    }

    internal class TokenTextListTableValuedParameterDefinition : TableValuedParameterDefinition<TokenTextListRow>
    {
        internal TokenTextListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.TokenTextList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NVarCharColumn Text = new NVarCharColumn("Text", 400, "Latin1_General_CI_AI");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, Text };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, TokenTextListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            Text.Set(record, 3, rowData.Text);
        }
    }

    internal struct TokenTextListRow
    {
        internal TokenTextListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.String Text)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.Text = Text;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.String Text { get; }
    }

    internal class TokenTokenCompositeSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<TokenTokenCompositeSearchParamListRow>
    {
        internal TokenTokenCompositeSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.TokenTokenCompositeSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly NullableIntColumn SystemId1 = new NullableIntColumn("SystemId1");
        internal readonly VarCharColumn Code1 = new VarCharColumn("Code1", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow1 = new NullableVarCharColumn("CodeOverflow1", -1, "Latin1_General_100_CS_AS");
        internal readonly NullableIntColumn SystemId2 = new NullableIntColumn("SystemId2");
        internal readonly VarCharColumn Code2 = new VarCharColumn("Code2", 256, "Latin1_General_100_CS_AS");
        internal readonly NullableVarCharColumn CodeOverflow2 = new NullableVarCharColumn("CodeOverflow2", -1, "Latin1_General_100_CS_AS");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, SystemId1, Code1, CodeOverflow1, SystemId2, Code2, CodeOverflow2 };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, TokenTokenCompositeSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            SystemId1.Set(record, 3, rowData.SystemId1);
            Code1.Set(record, 4, rowData.Code1);
            CodeOverflow1.Set(record, 5, rowData.CodeOverflow1);
            SystemId2.Set(record, 6, rowData.SystemId2);
            Code2.Set(record, 7, rowData.Code2);
            CodeOverflow2.Set(record, 8, rowData.CodeOverflow2);
        }
    }

    internal struct TokenTokenCompositeSearchParamListRow
    {
        internal TokenTokenCompositeSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.Nullable<System.Int32> SystemId1, System.String Code1, System.String CodeOverflow1, System.Nullable<System.Int32> SystemId2, System.String Code2, System.String CodeOverflow2)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.SystemId1 = SystemId1;
            this.Code1 = Code1;
            this.CodeOverflow1 = CodeOverflow1;
            this.SystemId2 = SystemId2;
            this.Code2 = Code2;
            this.CodeOverflow2 = CodeOverflow2;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.Nullable<System.Int32> SystemId1 { get; }
        internal System.String Code1 { get; }
        internal System.String CodeOverflow1 { get; }
        internal System.Nullable<System.Int32> SystemId2 { get; }
        internal System.String Code2 { get; }
        internal System.String CodeOverflow2 { get; }
    }

    internal class UriSearchParamListTableValuedParameterDefinition : TableValuedParameterDefinition<UriSearchParamListRow>
    {
        internal UriSearchParamListTableValuedParameterDefinition(System.String parameterName) : base(parameterName, "dbo.UriSearchParamList")
        {
        }

        internal readonly SmallIntColumn ResourceTypeId = new SmallIntColumn("ResourceTypeId");
        internal readonly BigIntColumn ResourceSurrogateId = new BigIntColumn("ResourceSurrogateId");
        internal readonly SmallIntColumn SearchParamId = new SmallIntColumn("SearchParamId");
        internal readonly VarCharColumn Uri = new VarCharColumn("Uri", 256, "Latin1_General_100_CS_AS");

        protected override global::System.Collections.Generic.IEnumerable<Column> Columns => new Column[] { ResourceTypeId, ResourceSurrogateId, SearchParamId, Uri };

        protected override void FillSqlDataRecord(global::Microsoft.Data.SqlClient.Server.SqlDataRecord record, UriSearchParamListRow rowData)
        {
            ResourceTypeId.Set(record, 0, rowData.ResourceTypeId);
            ResourceSurrogateId.Set(record, 1, rowData.ResourceSurrogateId);
            SearchParamId.Set(record, 2, rowData.SearchParamId);
            Uri.Set(record, 3, rowData.Uri);
        }
    }

    internal struct UriSearchParamListRow
    {
        internal UriSearchParamListRow(System.Int16 ResourceTypeId, System.Int64 ResourceSurrogateId, System.Int16 SearchParamId, System.String Uri)
        {
            this.ResourceTypeId = ResourceTypeId;
            this.ResourceSurrogateId = ResourceSurrogateId;
            this.SearchParamId = SearchParamId;
            this.Uri = Uri;
        }

        internal System.Int16 ResourceTypeId { get; }
        internal System.Int64 ResourceSurrogateId { get; }
        internal System.Int16 SearchParamId { get; }
        internal System.String Uri { get; }
    }
}