name: Build and deploy FHIR Server to Azure Web App - staging-fhir-server

on:
  push:
    branches:
      - fhir-qa
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.305'  # Match global.json requirement
          
      - name: Build with dotnet
        run: dotnet build src/Microsoft.Health.Fhir.R4.Web/Microsoft.Health.Fhir.R4.Web.csproj --configuration Release

      - name: dotnet publish FHIR R4
        run: dotnet publish src/Microsoft.Health.Fhir.R4.Web/Microsoft.Health.Fhir.R4.Web.csproj -c Release -f net9.0 -r win-x86 --self-contained true -o "${{env.DOTNET_ROOT}}/fhirapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-fhir-app
          path: ${{env.DOTNET_ROOT}}/fhirapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v8
        with:
          name: .net-fhir-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'staging-fhir-server'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_396B879ACB6441839D04D408149178E9 }}
